migrate(
  (app) => {
    const patients = app.findCollectionByNameOrId('patients')
    if (!patients.fields.getByName('cep')) patients.fields.add(new TextField({ name: 'cep' }))
    if (!patients.fields.getByName('logradouro'))
      patients.fields.add(new TextField({ name: 'logradouro' }))
    if (!patients.fields.getByName('numero')) patients.fields.add(new TextField({ name: 'numero' }))
    if (!patients.fields.getByName('bairro')) patients.fields.add(new TextField({ name: 'bairro' }))
    if (!patients.fields.getByName('cidade')) patients.fields.add(new TextField({ name: 'cidade' }))
    if (!patients.fields.getByName('estado')) patients.fields.add(new TextField({ name: 'estado' }))
    if (!patients.fields.getByName('pais')) patients.fields.add(new TextField({ name: 'pais' }))

    if (!patients.fields.getByName('billing_cep'))
      patients.fields.add(new TextField({ name: 'billing_cep' }))
    if (!patients.fields.getByName('billing_logradouro'))
      patients.fields.add(new TextField({ name: 'billing_logradouro' }))
    if (!patients.fields.getByName('billing_numero'))
      patients.fields.add(new TextField({ name: 'billing_numero' }))
    if (!patients.fields.getByName('billing_bairro'))
      patients.fields.add(new TextField({ name: 'billing_bairro' }))
    if (!patients.fields.getByName('billing_cidade'))
      patients.fields.add(new TextField({ name: 'billing_cidade' }))
    if (!patients.fields.getByName('billing_estado'))
      patients.fields.add(new TextField({ name: 'billing_estado' }))
    if (!patients.fields.getByName('billing_pais'))
      patients.fields.add(new TextField({ name: 'billing_pais' }))
    app.save(patients)

    const config = app.findCollectionByNameOrId('config_clinica')
    if (!config.fields.getByName('cep')) config.fields.add(new TextField({ name: 'cep' }))
    if (!config.fields.getByName('logradouro'))
      config.fields.add(new TextField({ name: 'logradouro' }))
    if (!config.fields.getByName('numero')) config.fields.add(new TextField({ name: 'numero' }))
    if (!config.fields.getByName('bairro')) config.fields.add(new TextField({ name: 'bairro' }))
    if (!config.fields.getByName('cidade')) config.fields.add(new TextField({ name: 'cidade' }))
    if (!config.fields.getByName('estado')) config.fields.add(new TextField({ name: 'estado' }))
    if (!config.fields.getByName('pais')) config.fields.add(new TextField({ name: 'pais' }))
    app.save(config)
  },
  (app) => {
    const patients = app.findCollectionByNameOrId('patients')
    patients.fields.removeByName('cep')
    patients.fields.removeByName('logradouro')
    patients.fields.removeByName('numero')
    patients.fields.removeByName('bairro')
    patients.fields.removeByName('cidade')
    patients.fields.removeByName('estado')
    patients.fields.removeByName('pais')
    patients.fields.removeByName('billing_cep')
    patients.fields.removeByName('billing_logradouro')
    patients.fields.removeByName('billing_numero')
    patients.fields.removeByName('billing_bairro')
    patients.fields.removeByName('billing_cidade')
    patients.fields.removeByName('billing_estado')
    patients.fields.removeByName('billing_pais')
    app.save(patients)

    const config = app.findCollectionByNameOrId('config_clinica')
    config.fields.removeByName('cep')
    config.fields.removeByName('logradouro')
    config.fields.removeByName('numero')
    config.fields.removeByName('bairro')
    config.fields.removeByName('cidade')
    config.fields.removeByName('estado')
    config.fields.removeByName('pais')
    app.save(config)
  },
)
